def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    ['-p', "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__],
  ).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

setup_permissions([
  'LocationWhenInUse',
  'LocationAlways',
])

# CodePush 9.0+ requires iOS 15.5 minimum.
platform :ios, '15.5'
prepare_react_native_project!
pod 'Firebase', :modular_headers => true
     pod 'FirebaseCore', :modular_headers => true
     pod 'GoogleUtilities', :modular_headers => true
     pod 'Firebase/Core'
     pod 'Firebase/Messaging'
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MaxxStation' do 
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
